### ISSUE TITLE
`session` object not being sent through appropriately

### ISSUE THREAD

**Issue by brettcannon** [python/bedevere#192]
```
2019-09-23T18:02:34.196871+00:00 app[web.1]:   File "/app/bedevere/bpo.py", line 81, in removed_label

2019-09-23T18:02:34.196873+00:00 app[web.1]:     await set_status(event, gh)

2019-09-23T18:02:34.196885+00:00 app[web.1]:   File "/app/bedevere/bpo.py", line 40, in set_status

2019-09-23T18:02:34.196901+00:00 app[web.1]:     issue_number_on_bpo = await _validate_issue_number(issue_number, session=session)

2019-09-23T18:02:34.196905+00:00 app[web.1]:   File "/app/bedevere/bpo.py", line 178, in _validate_issue_number

2019-09-23T18:02:34.196906+00:00 app[web.1]:     async with session.head(url) as res:

2019-09-23T18:02:34.196936+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'head'
```

**Comment by lysnikolaou** [comment]
This is a bug, I introduced in #159. I'll push a fix ASAP. Sorry!

**Comment by brettcannon** [comment]
@lysnikolaou it happens. 😄 Key thing is to figure out what testing didn't pick it up.

And when you say, "ASAP", do you mean today or later than that? I can try to get a fix out today if you don't have the time.

**Comment by lysnikolaou** [comment]
@brettcannon I could probably have something ready in 5-6 hours, I'm not 100% sure though.

**Comment by brettcannon** [comment]
@lysnikolaou OK, make sure to check this issue before you start to see if I left a message that I have started doing the work and I'll do the same. That way no one wastes their time and while still prioritizing getting a fix out.

**Comment by brettcannon** [comment]
I'm working on a fix.
